# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160601_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='block',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
